# This is jinja-tree configuration file for the needs
# of this specific repository.

# If you are looking for the default configuration file, 
# you will find it under docs/ directory.

[general]

context_generated_comment_line2 = "To modify this file, edit {{relative_filepath}} and launch 'make doc'"
context_plugins = [
    "jinja_tree.infra.adapters.context.ConfigurationContextAdapter",
    "jinja_tree.infra.adapters.context.EnvContextAdapter",
    "tools.jinja_tree_plugins.context.CustomEnvContextAdapter",
]


[context.config]

# Default value for BASEURL (can be overriden, for example for publishing the README.md file to PyPi)
BASEURL = ""
