pull_request_rules:

  - name: Automatic merge
    conditions:
      - "-label=Merge: Manual"
      - "label~=^Type:"
    actions:
      queue:


queue_rules:

  - name: default
    merge_method: squash
    commit_message_template: '{{ title }}'
    queue_conditions:
      - or:
          - check-success = mergify-ci-status
          - "-files~=^(?!CHANGELOG\\.md$).*$"
      - "-draft"
      - "-closed"
      - "-conflict"
      - "label~=^Type:.*"
      - or:
          - "author=fabien-marty"
          - "#approved-reviews-by >= 1"
merge_protections_settings:
  reporting_method: check-runs
