version: '3'

includes:
  uv: .task/taskfiles/Taskfile-python-uv.yml
  misc: .task/taskfiles/Taskfile-misc.yml

vars:
  DEFAULT_IMAGE: 'docker.io/library/jinja-tree'
  IMAGE: '{{ .IMAGE | default .DEFAULT_IMAGE }}'
  ECHO_OK: '{{ .ROOT_DIR }}/.task/taskfiles/utils/echo_ok'

tasks:

  clean:
    desc: "Clean the repository"
    cmds:
      - task: uv:clean

  mrproper:
    desc: "Clean the repository (including downloaded tools)"
    deps: 
      - clean
    cmds:
      - task: uv:mrproper

  install:
    desc: "Install the venv" 
    deps:
      - uv:sync

  lint:
    desc: "Lint the code"
    deps:
      - uv:lint

  test:
    desc: "Test the code"
    deps:
      - uv:test

  doc:
    desc: "Generate documentation"
    deps:
      - install
    cmds:
      - "{{.UV}} run python jinja_tree/infra/controllers/cli_tree.py ."

  docker:
    desc: "Build docker image"
    deps:
      - install
    cmds:
      - "docker build --progress plain -t myapp ."

  no-dirty:
    desc: "Check that the repository is clean"
    silent: true
    cmds:
      - task: misc:no-dirty
      - '{{.ECHO_OK}} "Repository is clean"'

  publish:
    desc: "Publish the package (to pypi)"
    cmds:
      - |
          if [ "${UV_PUBLISH_TOKEN:-}" = "" ]; then
            echo "UV_PUBLISH_TOKEN is not set"
            exit 1
          fi
      - task: uv:build
      - task: uv:publish
