#############################
### General configuration ###
#############################
# (Note: all values here are the default values)

[general]

# Search paths to jinja"
extra_search_paths = []

# Add root dir to search path (if true)
add_root_dir_to_search_path = true

# Add current working dir (CWD at script start) to search path (if true)
add_cwd_to_search_path = true

# Add processed file dir to search path (if true)
add_processed_file_dir_to_search_path = false

# Change working directory when tree walking (if true)
change_cwd = true

# Crash when templates use undefined variables (if true)
strict_undefined = true

# Disable embedded jinja extensions (if true)
# List of embedded jinja extensions (for information only):
# - jinja_tree.app.embedded_extensions.from_json.FromJsonExtension
# - jinja_tree.app.embedded_extensions.shell.ShellExtension
# - jinja_tree.app.embedded_extensions.fnmatch.FnMatchExtension
# - jinja_tree.app.embedded_extensions.double_quotes.DoubleQuotesExtension
# - jinja_tree.app.embedded_extensions.urlencode.UrlEncodeExtension
disable_embedded_jinja_extensions = false

# Jinja extensions to add (full paths)
# Notes: 
# - jinja-tree provides embedded extensions which will be added automatically to this list
# - you can disable embedded extensions with 'disable_embedded_jinja_extensions = true'
jinja_extensions = []

# Context plugin full classpaths
context_plugins = ["jinja_tree.infra.adapters.context.ConfigurationContextAdapter", "jinja_tree.infra.adapters.context.EnvContextAdapter", "jinja_tree.infra.adapters.context.DotEnvContextAdapter"]

# Generated comment template: line1 for context
# Available placeholders: {{utcnow}}, {{absolute_path}}, {{dirname}}, {{basename}}, {{relative_filepath}}
context_generated_comment_line1 = "*** GENERATED FILE - DO NOT EDIT ***"

# Generated comment template: line2 for context
# Available placeholders: {{utcnow}}, {{absolute_path}}, {{dirname}}, {{basename}}, {{relative_filepath}}
context_generated_comment_line2 = "This file was generated by jinja-tree (https://github.com/fabien-marty/jinja-tree) from the template file: {{relative_filepath}}"

# Action plugin full classpaths
action_plugins = ["jinja_tree.infra.adapters.action.ExtensionsActionAdapter"]


######################################
### Context plugins configurations ###
######################################
[context.env]

# Fnmatch patterns (for environment variable names) to ignore
# Example: ["FOO*", "*BAR"]  for ignoring all env var starting with FOO or ending with BAR
ignores = []

[context.dotenv]

# dotenv file path (absolute or relative), if set to an empty string (""), dotenv support is disabled 
path = ".env"

# Fnmatch patterns (for dotenv variable names) to ignore
# Example: ["FOO*", "*BAR"]  for ignoring all dotenv var starting with FOO or ending with BAR
ignores = []

[context.config]

# With the ConfigurationContextAdapter plugin, you can add key/values below, they will be available in Jinja2 context

# [...]


##########################################  
### File-action plugins configurations ###
##########################################
[action.extension]

# File extensions to process
# Example: [".j2", ".jinja2", ".template"] for processing all files ending with .j2, .jinja2 or .template
extensions = [".template"]

# Filename patterns to ignore (fnmatch patterns to match against basename only)
filename_ignores = [ ".*" ]

# Dirname patterns to ignore recursively (fnmatch patterns to match against dirname only)
dirname_ignores =  [ "venv", "site-packages", "__pypackages__", "node_modules", "__pycache__", ".*" ]

# Replace target files if they already exist (if true)
replace = true

# Delete original (template) file after processing (if true)
delete_original = false