#############################
### General configuration ###
#############################
# (Note: all values here are the default values)

[general]

# Search paths to jinja"
extra_search_paths = []

# Add root dir to search path (if true)
add_root_dir_to_search_path = true

# Add current working dir (CWD at script start) to search path (if true)
add_cwd_to_search_path = true

# Add processed file dir to search path (if true)
add_processed_file_dir_to_search_path = false

# Change working directory when tree walking (if true)
change_cwd = true

# Crash when templates use undefined variables (if true)
strict_undefined = true

# Delete original (template) file after processing (if true)
delete_original = false

# Disable embedded jinja extensions (if true)
# List of embedded jinja extensions (for information only):
# - jinja_tree.app.embedded_extensions.from_json.FromJsonExtension
# - jinja_tree.app.embedded_extensions.shell.ShellExtension
# - jinja_tree.app.embedded_extensions.fnmatch.FnMatchExtension
# - jinja_tree.app.embedded_extensions.double_quotes.DoubleQuotesExtension

disable_embedded_jinja_extensions = false

# Jinja extensions to add (full paths)
# Notes: 
# - jinja-tree provides embedded extensions which will be added automatically to this list
# - you can disable embedded extensions with 'disable_embedded_jinja_extensions = true'
jinja_extensions = []


####################################  
### Context plugin configuration ###
####################################  
[context]

# Plugin full classpath [common key for all context plugins]
plugin = "jinja_tree.infra.adapters.context.EnvContextAdapter"

# Generated comment template: line1 [common key for all context plugins]
# Available placeholders: {utcnow}, {absolute_path}, {dirname}, {basename}, {relative_filepath}
generated_comment_line1 = "*** GENERATED FILE - DO NOT EDIT ***"

# Generated comment template: line2 [common key for all context plugins]
# Available placeholders: {utcnow}, {absolute_path}, {dirname}, {basename}, {relative_filepath}
generated_comment_line2 = "This file was generated by jinja-tree (https://github.com/fabien-marty/jinja-tree) from the template file: {{relative_filepath}}"

# Fnmatch patterns (for environment variable names) to ignore [specific to EnvContextAdapter plugin]
# Example: ["FOO*", "*BAR"]  for ignoring all env var starting with FOO or ending with BAR
env_ignores = []

# dotenv file path (absolute or relative), if set to an empty string (""), dotenv support is disabled [specific to EnvContextAdapter plugin]
dotenv_path = ".env"

# Fnmatch patterns (for dotenv variable names) to ignore [specific to EnvContextAdapter plugin]
# Example: ["FOO*", "*BAR"]  for ignoring all dotenv var starting with FOO or ending with BAR
dotenv_ignores = []

# Fnmatch patterns (for plugin_configuration variable names) to ignore [specific to EnvContextAdapter plugin]
# Example: ["foo*", "*bar"]  for ignoring all plugin configuration var starting with foo or ending with bar
plugin_configuration_ignores = ["plugin", "generated_comment_line1", "generated_comment_line2", "env_ignores", "dotenv_path", "dotenv_ignores", "plugin_configuration_ignores"]

# With the EnvContextAdapter plugin, you can add key/values below, they will be available in Jinja2 context

# [...]


########################################  
### File-action plugin configuration ###
########################################
[action]

# Plugin full classpath [common key for all file-action plugins]
plugin = "jinja_tree.infra.adapters.action.ExtensionsFileActionAdapter"

# File extensions to process [specific to ExtensionsFileActionAdapter plugin]
# Example: [".j2", ".jinja2", ".template"] for processing all files ending with .j2, .jinja2 or .template
extensions = [".template"]

# Filename patterns to ignore (fnmatch patterns to match against basename only)
filename_ignores = [ ".*" ]

# Dirname patterns to ignore recursively (fnmatch patterns to match against dirname only)
dirname_ignores =  [ "venv", "site-packages", "__pypackages__", "node_modules", "__pycache__", ".*" ]

# Replace target files if they already exist (if true)
replace = true